UV-54 - Proper handling of validation errors
absmach/magistrala-ui pull request #1
Opened 2023-11-07 13:07 UTC by Musilah

### What does this do?
Provides for some errors by providing more details as to the validation apart from just malformed entity specification.
### Which issue(s) does this PR fix/relate to?
resolves #54
### List any changes that modify/break current functionality
None
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
![image](https://github.com/absmach/magistrala-ui/assets/115026536/09b2c2d5-ac1e-48c7-986b-fe35ba1b029c)
![Screenshot from 2023-12-20 14-03-18](https://github.com/absmach/magistrala-ui/assets/115026536/0ba03a94-3950-4f3e-93a3-397346e33db3)

2023-12-19 10:24 UTC, rodneyosodo requested changes

2023-12-19 10:24 UTC, rodneyosodo commented on ui/api/errors.go
> +import "github.com/mainflux/mainflux/pkg/errors"
Should be magistrala

2023-12-20 08:53 UTC, ianmuchyri requested changes

2023-12-20 08:53 UTC, ianmuchyri commented on ui/api/requests.go
> +	if req.Metadata == nil {
this separation of name and metadata is causing the update entities not to work. This is because If you update the name, metadata will be empty and bring an error and vice-versa. If you are going to split them you can always include both of them in the form submitted or split the endpoints for updating names and for updating metadata

This also applies to the other updates

2023-12-20 08:57 UTC, Musilah commented on ui/api/requests.go
> +	if req.Metadata == nil {
I will put them back as they were.

2023-12-21 08:08 UTC, ianmuchyri requested changes

2023-12-21 08:08 UTC, ianmuchyri commented on ui/api/transport.go
> +	case errFileFormat:
put this in the first case, since it's the same as the those

2023-12-21 08:08 UTC, ianmuchyri commented on ui/web/static/js/forms.js
>              showAlert("invalid file type!", config.alertDiv);
since the error is also encoded in the header, fetch the error message for this from the headers instead of the hard coded message

2023-12-21 08:08 UTC, ianmuchyri commented on ui/web/static/js/forms.js
>              showAlert("invalid file type!", config.alertDiv);
same for the others. Lets remove the hard coded messages, and let the messages come from the back end

2023-12-21 11:31 UTC, dborovcanin approved these changes

2023-12-21 11:53 UTC, dborovcanin requested changes

2023-12-21 11:53 UTC, dborovcanin commented on go.mod
> +	github.com/mainflux/mainflux v0.12.0
Let's switch to Magistrala SenML v1.0.5. so we do not depend on Mainflux anymore.

2023-12-21 18:44 UTC, ianmuchyri approved these changes
LGTM

2023-12-21 21:51 UTC, dborovcanin approved these changes

2023-12-21 21:51 UTC, merged