MG-93 - Add support for creating charts
absmach/magistrala-ui pull request #103
Opened 2024-01-30 07:46 UTC by Musilah

# What type of PR is this?

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
This creates configurable chart templates that will be added to the widgets. 

- The charts should be configurable
- The charts should be able to use the SENML data format used in Magistrala

## Which issue(s) does this PR fix/relate to?

- Related Issue #81
- Resolves #93

## Have you included tests for your changes?

- [ ] Yes
- [X] No

## Did you document any new/modified functionality?

- [ ] Yes
- [X] No

### Notes

2024-01-31 11:24 UTC, dborovcanin commented
@Musilah Please resolve the conflicts and mark as _Ready for review_ when it's ready.

2024-01-31 11:32 UTC, dborovcanin reviewed
Add a separate `templates` subdirectory for charts and charts modals.

2024-02-01 08:50 UTC, ianmuchyri requested changes

2024-02-01 08:50 UTC, ianmuchyri commented on package-lock.json
> -        "prettier": "^3.1.0",
why are you removing the prettier dependency? It's used for prettier formatting

2024-02-01 08:50 UTC, ianmuchyri commented on ui/jsonObject.go
>  			Widget:  "lineChart",
rename this file to a more descriptive name.

2024-02-01 08:50 UTC, ianmuchyri commented on ui/jsonObject.go
>  			Widget:  "lineChart",
and remove the to be deleted comment

2024-02-01 08:50 UTC, ianmuchyri commented on ui/jsonObject.go
>  			Title:   "Line Chart",
Line chart is being repeated a couple of times

2024-02-01 11:35 UTC, ianmuchyri requested changes

2024-02-01 11:35 UTC, ianmuchyri commented on ui/charts.go
> +			Image:   "https://example.com/image1.jpg",
remove the image field if we are not using it. If we are using it, find relevant open source images to use for the images

2024-02-01 17:22 UTC, ianmuchyri requested changes

2024-02-01 17:22 UTC, ianmuchyri commented on ui/web/templates/charts/dynamicdatachartmodal.html
> +                const categories = (function () {
use `var` instead of `const`

2024-02-01 21:24 UTC, dborovcanin requested changes
Newly added widgets are not resizable. However, if I first save and after that enter edit mode, I can see the resize option.

2024-02-02 07:40 UTC, ianmuchyri approved these changes

2024-02-02 08:19 UTC, dborovcanin approved these changes

2024-02-02 08:20 UTC, merged