MG-94 - Add storage for dashboards
absmach/magistrala-ui pull request #104
Opened 2024-01-30 18:04 UTC by 1998-felix

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Adds postgress implementation for storage of dashboards

## Which issue(s) does this PR fix/relate to?

- Resolves #94

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why:  will do so

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-02-02 13:05 UTC, ianmuchyri requested changes

2024-02-02 13:05 UTC, ianmuchyri commented on ui/service.go
> +	err = us.drepo.Update(context.Background(), dashboard)
return just the error. Sth like how we do for the other entities e.g:
```
func (us *uiService) UpdateThing(token string, thing sdk.Thing) error {
	if _, err := us.sdk.UpdateThing(thing, token); err != nil {
		return errors.Wrap(err, ErrFailedUpdate)
	}

	return nil
}
```

2024-02-02 13:05 UTC, ianmuchyri commented on postgres/dashboards.go
> +	q := `SELECT dashboard_id, user_id, dashboard_name, description, metadata, layout FROM dashboards WHERE user_id = :user_id`
when retrieving all dashboards do not return the layout (this will make the data too large). The layout will be returned when the user selects a specific dashboard

2024-02-02 14:39 UTC, ianmuchyri requested changes

2024-02-02 14:39 UTC, ianmuchyri commented on ui/service.go
> +	items["data"] = dashboardsPage.Dashboards
```suggestion
	items["dashboards"] = dashboardsPage.Dashboards
```

2024-02-02 14:39 UTC, ianmuchyri commented on ui/api/metrics.go
> +// View Dashboards adds metrics middleware to view dashboards method.
```suggestion
// View Dashboards adds metrics middleware to view dashboard method.
```

2024-02-02 14:39 UTC, ianmuchyri commented on ui/api/logging.go
> +// View Dashboards adds logging middleware to dashboards method.
```suggestion
// View Dashboards adds logging middleware to dashboard method.
```

2024-02-05 07:58 UTC, ianmuchyri requested changes

2024-02-05 07:58 UTC, ianmuchyri commented on docker/docker-compose.yml
> +        MG_POSTGRES_MAX_CONNECTIONS: ${MG_POSTGRES_MAX_CONNECTIONS}
add empty line

2024-02-05 07:58 UTC, ianmuchyri commented on docker/.env
> +MG_UI_PORT=9096
no need for the UI port change

2024-02-05 07:58 UTC, ianmuchyri commented on internal/postgres/postgres.go
> +func SetupDB(cfg Config, migrations migrate.MemoryMigrationSource) (*sqlx.DB, error) {
Can the three functions `Setup`, `SetupwithConfig` and `SetupDB`, be combined to one function 
```
Setup(prefix string, cfg Config, migrations migrate.MemoryMigrationSource)(*sqlx.DB, error){
  if err := env.Parse(&cfg, env.Options{Prefix: prefix}); err != nil {
		  return nil, errors.Wrap(errConfig, err)
	  }
  db, err := Connect(cfg)
  if err != nil {
    return nil, err
   }
  
  _, err = migrate.Exec(db.DB, "postgres", migrations, migrate.Up)
  if err != nil {
   return nil, errors.Wrap(errMigration, err)
  }
  
  return db, nil
}
```

2024-02-05 07:58 UTC, ianmuchyri commented on internal/env/parser.go
> +import "github.com/caarlos0/env/v7"
You don't need this package `env`, using [caarlos0 v9](github.com/caarlos0/env/v9), you can just parse the environment variables directly
```
	cfg := config{}
	if err := env.Parse(&cfg); err != nil {
		log.Fatalf(err.Error())
	}
```

2024-02-05 07:58 UTC, ianmuchyri commented on postgres/dashboards.go
> +    INSERT INTO dashboards (dashboard_id, user_id, dashboard_name, description, metadata, layout)
Add more parameters, replace `user_id` with `created_by`, add `created_at`, `updated_at`

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +// View Dashboards adds logging middleware to view dashboard method.
```suggestion
// View Dashboard adds logging middleware to view dashboard method.
```

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +		args := []interface{}{
```suggestion
		args := []any{
```

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +		args := []interface{}{
```suggestion
		args := []any{
```

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +		args := []interface{}{
no need for an interface for just one argument

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +		args := []interface{}{
```suggestion
		args := []any{
```

2024-02-05 07:58 UTC, ianmuchyri commented on ui/api/logging.go
> +		args := []interface{}{
```suggestion
		args := []any{
```

2024-02-05 10:46 UTC, ianmuchyri requested changes

2024-02-05 10:46 UTC, ianmuchyri commented on ui/service.go
> +		UpdatedAt:     time.Now(),
We don't populate `UpdateAt` during creation

2024-02-05 10:46 UTC, ianmuchyri commented on ui/dashboards.go
> +	DashboardID   string    `json:"dashboard_id,omitempty" db:"dashboard_id"`
some of these fields are not supposed to be `omitempty` such as `dashboard_id`, `dashboard_name`, `created_by`, `layout`, `created_at`

2024-02-05 10:46 UTC, ianmuchyri commented on docker/.env
> +MG_UI_HOST_URL=http://localhost:9096
```suggestion
MG_UI_HOST_URL=http://localhost:9095
```

2024-02-05 10:46 UTC, ianmuchyri commented on docker/docker-compose.yml
> +  magistrala-ui-net:
```suggestion
  magistrala-base-net:
```

2024-02-05 10:46 UTC, ianmuchyri commented on docker/docker-compose.yml
> +    container_name: magistrala-ui-standalone
```suggestion
    container_name: magistrala-ui
```

2024-02-05 10:46 UTC, ianmuchyri commented on docker/docker-compose.yml
> +      container_name: magistrala-ui-standalone-db
```suggestion
      container_name: magistrala-ui-db
```

2024-02-05 10:46 UTC, ianmuchyri commented on docker/docker-compose.yml
> +        - magistrala-ui-net
```suggestion
        - magistrala-base-net
```

2024-02-05 10:46 UTC, ianmuchyri commented on docker/docker-compose.yml
> +      - magistrala-ui-net
```suggestion
      - magistrala-base-net
```

2024-02-05 12:15 UTC, ianmuchyri requested changes

2024-02-05 12:15 UTC, ianmuchyri commented on ui/service.go
> +	entropy := rand.New(rand.NewSource(time.Now().UnixNano()))
for uniformity of the id's I suggest you use the Magistrala format for uuid: https://github.com/absmach/magistrala/blob/main/pkg/uuid/uuid.go

2024-02-05 12:15 UTC, ianmuchyri commented on postgres/dashboards.go
> +	q := `SELECT dashboard_id, created_by, dashboard_name, description, metadata, created_at, updated_at FROM dashboards WHERE created_by = :created_by LIMIT :limit OFFSET :offset`
`ORDER BY created_at` to retrieve beginning with the latest dashboard

2024-02-05 13:42 UTC, ianmuchyri requested changes

2024-02-05 13:42 UTC, ianmuchyri commented on docker/docker-compose.yml
> +        - 6044:5432
```suggestion
        - 6042:5432
```

2024-02-05 13:45 UTC, ianmuchyri requested changes

2024-02-05 13:45 UTC, ianmuchyri commented on postgres/dashboards.go
> +	RETURNING dashboard_id, created_by, dashboard_name, description, metadata, layout, created_at, updated_at`
```suggestion
	RETURNING dashboard_id, created_by, dashboard_name, description, metadata, layout, created_at
```

2024-02-05 14:06 UTC, ianmuchyri approved these changes

2024-02-05 15:03 UTC, Musilah approved these changes

2024-02-05 15:28 UTC, dborovcanin requested changes

2024-02-05 15:28 UTC, dborovcanin commented on postgres/init.go
> +						description TEXT,
No need for a `dashboard` prefix for ID and name.

2024-02-05 15:28 UTC, dborovcanin commented on ui/api/endpoint.go
> +			code: http.StatusOK,
Since we do not return anything else, the correct code would be No Content. Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE.

2024-02-05 15:28 UTC, dborovcanin commented on postgres/init.go
> +						metadata TEXT,
For other entities it is added as the option for extension, but we probably do not need metadata for dashboards. Please remove.

2024-02-05 22:19 UTC, dborovcanin approved these changes

2024-02-05 22:19 UTC, merged