MG-93 - Add support for billboard.js charts
absmach/magistrala-ui pull request #117
Opened 2024-02-05 12:13 UTC by Musilah

# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

- [ ] Yes
- [ ] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [ ] No, and this is why: 

### Notes

2024-02-09 07:12 UTC, 1998-felix requested changes

2024-02-09 07:12 UTC, 1998-felix commented on ui/web/templates/charts/doublebarchartmodal.html
> +          <h5 class="modal-title" id="doubleBarChartModalLabel">Time series bar chart</h5>
The name on thre title of the modal and on the card do not match. Should they not be the same?

2024-02-09 07:12 UTC, 1998-felix commented on ui/web/templates/charts/multigaugemodal.html
> +          <h5 class="modal-title" id="multiGaugeModalLabel">Time series line charts</h5>
Same as above.

2024-02-09 07:19 UTC, 1998-felix reviewed
![image](https://github.com/absmach/magistrala-ui/assets/57312311/4203c020-12e0-47a2-8970-98189bb9d170)
The multigauge modal and the double bar chart.

2024-02-09 10:37 UTC, 1998-felix commented on ui/charts.go
> +			Title:   "mutliple line Chart",
Capitalize

2024-02-09 14:56 UTC, 1998-felix commented
This pr removes thumbnails which will be returned by addressing issue: https://github.com/absmach/magistrala-ui/issues/149

2024-02-09 14:56 UTC, dborovcanin requested changes
Resizing the newly added charts does not work properly.

2024-02-12 10:17 UTC, ianmuchyri commented
All these charts you are adding seem to also be in the e-charts library. Did you check there?

2024-02-12 14:05 UTC, ianmuchyri requested changes

2024-02-13 07:24 UTC, ianmuchyri approved these changes

2024-02-13 07:46 UTC, 1998-felix approved these changes

2024-02-13 09:40 UTC, dborovcanin approved these changes

2024-02-13 09:40 UTC, merged