NOISSUE - Implement registration page
absmach/magistrala-ui pull request #119
Opened 2024-02-06 11:49 UTC by rodneyosodo

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

Implements registration page

## Which issue(s) does this PR fix/relate to?

No issue

## Have you included tests for your changes?

- [x] Yes
- [ ] No, and this is why: 

## Did you document any new/modified functionality?

- [x] Yes
- [ ] No, and this is why: 

### Notes

![image](https://github.com/absmach/magistrala-ui/assets/28790446/72e52f28-dd22-4547-8334-38a27609c318)

![image](https://github.com/absmach/magistrala-ui/assets/28790446/579f38fc-cad0-4f97-b6fa-401653f560bd)

2024-02-06 13:19 UTC, ianmuchyri requested changes

2024-02-06 13:19 UTC, ianmuchyri commented on ui/web/templates/registration.html
> +                  passwordField.classList.add("border-red");
add `border-red` for the `nameField` too

2024-02-06 13:23 UTC, ianmuchyri requested changes

2024-02-06 13:23 UTC, ianmuchyri commented on ui/web/templates/registration.html
> +                case 401:
This code `case 401` is not addressed anywhere in the back-end hence, it will not reflect.

2024-02-07 09:10 UTC, ianmuchyri requested changes

2024-02-07 09:10 UTC, ianmuchyri commented on ui/web/templates/registration.html
> +
```
document.getElementById("register-button").addEventListener("click", () => {
         registrationError.innerHTML = "";
        });
```

add sth similar to the login page. It helps overcome this issue
![image](https://github.com/absmach/magistrala-ui/assets/100555904/7f63437a-e833-4e13-b9fe-c93f9c74e740)

Incase the user had tried creating an existing user, then they make another mistake the second time trying

2024-02-07 09:10 UTC, ianmuchyri commented on ui/web/templates/registration.html
> +          <div class="login-card col-lg-4 p-md-5 mx-auto mt-5">
```suggestion
          <div class="login-card col-lg-4 p-md-5 mx-auto mt-4">
```

to remove the overflow occuring

2024-02-07 09:54 UTC, rodneyosodo commented on ui/web/templates/registration.html
> +          <div class="login-card col-lg-4 p-md-5 mx-auto mt-5">
This is the top margin of the login card and will not change content from overflowing.

Content overflows because the text is bigger than the width of the container and it is perfectly normal. For example 
![image](https://github.com/absmach/magistrala-ui/assets/28790446/4d1ba86b-c0c0-4403-aece-f9bd06b7f93e)

2024-02-07 10:25 UTC, ianmuchyri approved these changes

2024-02-07 10:32 UTC, dborovcanin commented on ui/web/templates/registration.html
> +        function showAlert(errorMessage) {
Rename to "showError" or something similar, since the alert can be confused for a built-in browser alert.

2024-02-07 10:38 UTC, dborovcanin approved these changes

2024-02-07 10:38 UTC, merged