MG-93 - Add bootstraps charts support
absmach/magistrala-ui pull request #122
Opened 2024-02-07 09:43 UTC by Musilah

# What type of PR is this?

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
This adds more charts from bootstrap

## Which issue(s) does this PR fix/relate to?

- Related Issue #93 

## Have you included tests for your changes?

- [ ] Yes
- [X] No 

## Did you document any new/modified functionality?

- [ ] Yes
- [X] No 

### Notes
The charts being added include: 
- value card
- value and chart card
- alarm count
- entity count
- alarm table
- entity table
- label card
- progress bar

2024-02-14 07:38 UTC, ianmuchyri commented
Fix the height styling. There is too much unnecessary space at the bottom

![image](https://github.com/absmach/magistrala-ui/assets/100555904/c850af6b-e6cf-45cb-a893-0bfdca3c9b0e)

2024-02-14 07:56 UTC, ianmuchyri requested changes

2024-02-14 07:56 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +    } else {
This only works for widgets with cards in them. For the rest with the tables and progress bar it does not work well check on that

![image](https://github.com/absmach/magistrala-ui/assets/100555904/cd9b33b2-1fb6-45cf-8a7e-3efed083d7f1)

2024-02-14 07:56 UTC, ianmuchyri commented on ui/web/templates/dashboard.html
> +{{ end }}
add empty line

2024-02-14 16:56 UTC, 1998-felix approved these changes
The resizing of the widgets is still not optimal but is being handled by issue https://github.com/absmach/magistrala-ui/issues/129

2024-02-14 17:03 UTC, ianmuchyri approved these changes

2024-02-15 00:09 UTC, dborovcanin approved these changes

2024-02-15 00:09 UTC, merged