MG-111- Populte charts with data from magistrala
absmach/magistrala-ui pull request #123
Opened 2024-02-07 10:13 UTC by 1998-felix

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Populate dashboard charts with data from magistrala.

## Which issue(s) does this PR fix/relate to?

- Resolves #111 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-02-12 09:32 UTC, ianmuchyri requested changes

2024-02-12 09:32 UTC, ianmuchyri commented on ui/web/templates/charts/horizontalbarchartmodal.html
> +            <div class="mb-3">
There is no appearance tab for this modal

2024-02-12 09:51 UTC, ianmuchyri requested changes

2024-02-12 09:51 UTC, ianmuchyri commented on ui/web/templates/charts/linechartmodal.html
> +      console.log(formData);
remove log

2024-02-12 09:51 UTC, ianmuchyri commented on ui/web/templates/charts/piechartmodal.html
> -              <label for="x-axis" class="form-label">Select x-axis Type</label>
In this chart you need to populate the chart with the form data

2024-02-12 09:56 UTC, ianmuchyri requested changes

2024-02-12 09:56 UTC, ianmuchyri commented on ui/web/templates/charts/stackedlinechartmodal.html
> +              data: ['Thing1', 'Thing2', 'Thing3', 'Thing4', 'Thing5', 'Thing6', 'Thing7'],
I am not able to see the x-axis label
![image](https://github.com/absmach/magistrala-ui/assets/100555904/82057b37-c34b-4882-a80a-25f7ff6e6a39)

2024-02-12 09:56 UTC, ianmuchyri commented on ui/web/templates/charts/dynamicdatachartmodal.html
> +        var form = document.getElementById("create-dynamicDataChart-appearance-form");
populate the chart appearance with data from the form

2024-02-12 11:25 UTC, dborovcanin commented on ui/web/templates/charts/arealinechartmodal.html
> +                    placeholder="Enter the time interval in seconds"
Seconds are fine. We can add minutes later if needed.

2024-02-12 11:26 UTC, dborovcanin requested changes
Please resolve conflicts.

2024-02-12 14:04 UTC, ianmuchyri requested changes

2024-02-12 14:04 UTC, ianmuchyri commented on ui/web/templates/charts/dynamicdatachartmodal.html
> +              data.shift();create-areaLineChart-button
```suggestion
              data.shift();
```

2024-02-13 07:01 UTC, ianmuchyri requested changes

2024-02-13 07:47 UTC, ianmuchyri approved these changes

2024-02-13 10:07 UTC, dborovcanin approved these changes

2024-02-13 10:07 UTC, merged