NOISSUE - Add placeholder to the canvas with no widget
absmach/magistrala-ui pull request #127
Opened 2024-02-07 14:40 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Adds a placeholder to the canvas during initialization if there is no widget to be placed on the canvas.
![image](https://github.com/absmach/magistrala-ui/assets/100555904/d4888211-c095-41a1-9678-573810b5765e)

## Which issue(s) does this PR fix/relate to?

- Related Issue #99 
- Resolves #

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes
depends on #108

2024-02-07 19:17 UTC, dborovcanin requested changes
When I click on adding widgets, but I exit from the sidebar without adding any widgets, the button is gone:
![image](https://github.com/absmach/magistrala-ui/assets/17817225/de03033f-07fc-4a86-b1fe-104dc08557f2)

2024-02-07 19:17 UTC, dborovcanin commented on ui/web/static/js/singleDashboard.js
> +        <span>Add Widget</span>
Use plural: "Add Widgets",

2024-02-09 11:18 UTC, ianmuchyri commented
> When I click on adding widgets, but I exit from the sidebar without adding any widgets, the button is gone: ![image](https://private-user-images.githubusercontent.com/17817225/303109626-de03033f-07fc-4a86-b1fe-104dc08557f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NTI5MDEsIm5iZiI6MTcwNzQ1MjYwMSwicGF0aCI6Ii8xNzgxNzIyNS8zMDMxMDk2MjYtZGUwMzAzM2YtMDdmYy00YTg2LWIxZmUtMTA0ZGMwODU1N2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDA0MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDJlMmY5NzZiN2Y1ODdmZWJkOGE2ZDc5ZjFhZGFmMjc0ODBiYjA4MGMyMjI1Y2U3MjQ5ZmFhZTkyNGUxZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TmR-85OovbnEyGm7Fl-LOY8DVX1GvCU4cKaAeJrcU6I)

This is because you are still in the edit mode for the canvas. If you click on the cancel button, it will take you back to the view mode where is no widget, it will appear again

2024-02-09 13:58 UTC, dborovcanin approved these changes

2024-02-09 14:00 UTC, merged