MG-139 - Store chart settings
absmach/magistrala-ui pull request #160
Opened 2024-02-15 06:41 UTC by 1998-felix

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Introduces capability to save chart settings along with the saved layout.

## Which issue(s) does this PR fix/relate to?

- Resolves #139 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-02-23 09:14 UTC, ianmuchyri requested changes

2024-02-23 09:14 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +    const widgetHeight = itemContent.style.height;
```suggestion
     const widgetWidth = itemElement.style.width;
     const widgetHeight = itemElement.style.height;
```

2024-02-23 09:14 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +    const itemContent = itemElement.querySelector(".item-content");
```suggestion
```

2024-02-23 09:14 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +          Type: itemData.widgetID.split("-")[0],
Why don't you just save this too same as the widgetID, you also save widgetType

2024-02-23 09:14 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +          // Apply saved size
```suggestion
          newItem.classList.add("item-editable");
```

2024-02-23 09:14 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
>          });
```suggestion
          resizeObserver.observe(newItem);
```

2024-02-23 09:28 UTC, ianmuchyri requested changes

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +        newItem.style.height = itemData.widgetSize.height;
```suggestion
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +        newItem.style.width = itemData.widgetSize.width;
```suggestion
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +        var styleString = `width: ${config.Style.width}; height: ${config.Style.height};`;
```suggestion
      var styleString = `width: ${itemData.widgetSize.width}; height: ${itemData.widgetSize.height};`;
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +          // Apply saved position
```suggestion
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +            </button>
```suggestion
        var styleString = `width: ${itemData.widgetSize.width}; height: ${itemData.widgetSize.height};`;
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
>            newItem.className = "item";
```suggestion
          newItem.className = "item";
          newItem.classList.add("item-editable");
```

2024-02-23 09:28 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +          grid.add(newItem, { layout: true });
```suggestion
          grid.add(newItem, { layout: true });
          resizeObserver.observe(newItem);
```

2024-02-23 12:15 UTC, ianmuchyri requested changes

2024-02-23 12:15 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +        newItem.classList.add("item-editable");
```suggestion
```

2024-02-23 12:15 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +        newItem.classList.add("item-editable");
This makes the widgets editable when not in edit mode

2024-02-23 12:15 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> -    const itemContent = itemElement.querySelector(".item-content");
return this. You are applying the width and height on the div element with class `item-content` . Be very careful with this since it affects the loading size. Know which elements you are saving the data for, and then when loading the widgets apply those data saved to exactly the elements you extracted them from. If you extracted properties for div with class `item` when loading load the properties to a div with class name `item`.

2024-02-23 12:29 UTC, ianmuchyri requested changes

2024-02-23 12:29 UTC, ianmuchyri commented on ui/web/templates/charts/alarmcountmodal.html
>        }
```suggestion
       let form = document.getElementById("create-lineChart-form");
      // Create an object to store the form data
      let chartData = {};
      let formData = new FormData(form);
      for (var pair of formData.entries()) {
        chartData[pair[0]] = pair[1];
      }
```

2024-02-23 12:29 UTC, ianmuchyri commented on ui/web/templates/charts/alarmcountmodal.html
>        }
Do this for the other charts as well. Also, it's better to use `let` instead of `var`.

2024-02-23 13:40 UTC, dborovcanin requested changes

2024-02-23 13:40 UTC, dborovcanin commented on postgres/dashboards.go
> +	ma, err := json.Marshal(ds.Metadata)
```go
md, err := ...
```

2024-02-23 13:40 UTC, dborovcanin commented on postgres/dashboards.go
> +	var ma string
Same here, use `md`.

2024-02-23 13:40 UTC, dborovcanin commented on ui/web/static/js/charts.js
> +function createChart(chartData, config) {
Is it possible to create an abstraction for the chart class where each object is in charge of returning a proper config for itself? This can be done later during planned refactoring.

2024-02-23 14:15 UTC, 1998-felix commented on ui/web/static/js/charts.js
> +function createChart(chartData, config) {
I will add a comment on the issue for the same.

2024-02-23 14:53 UTC, ianmuchyri approved these changes

2024-02-26 10:41 UTC, dborovcanin approved these changes

2024-02-26 10:41 UTC, merged