NOISSUE - Update session management
absmach/magistrala-ui pull request #187
Opened 2024-02-21 19:04 UTC by ianmuchyri

# What type of PR is this?

- [] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Updates the session management. When the user logs in or registers, the user is redirected to the /domains page with the URL containing the access and refresh token e.g.`/domains?access_token=123&refresh_token=123`. These tokens are then added to the browser page when loading the page. When a user logs in the domain tokens are saved in the cookies. Furthermore, we introduce a `session cookie` that saves the user details in the browser. The stored cookies will be secured in the pr addressing this issue #182 

## Which issue(s) does this PR fix/relate to?

NOISSUE

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-02-22 08:32 UTC, rodneyosodo requested changes

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
> +type SessionDetails struct {
You can Embed User and Domain for example

```go
type SessionDetails struct {
	User struct {
		ID       string `json:"id"`
		Name     string `json:"name"`
		Identity string `json:"identity"`
		Role     string `json:"role"`
	} `json:"user"`
	Domain struct {
		ID          string   `json:"id"`
		Name        string   `json:"name"`
		Permissions []string `json:"permissions"`
	} `json:"domain"`
	LoginStatus string `json:"login_status"`
}
```

Also no need of exporting elements if they are not used outside the package

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
>  		if errors.Contains(err, ErrConflict) {
This code block seems redundant
```go
if errors.Contains(err, ErrConflict) {
	return []byte{}, errors.Wrap(err, ErrConflict)
}
```

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
>  	_, err := us.sdk.CreateUser(user, "")
Inline

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
> +	jsonData, err := json.Marshal(token)
```suggestion
	data, err := json.Marshal(token)
```

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
> +	SessionDetails(token, session, domainID string) (string, error)
```suggestion
	Session(token, session, domainID string) (string, error)
```

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
> +	}
Add default case and handle the error

2024-02-22 08:32 UTC, rodneyosodo commented on ui/service.go
> +	jsonData, err := json.Marshal(sessionDetails)
```suggestion
	data, err := json.Marshal(sessionDetails)
```

2024-02-22 08:32 UTC, rodneyosodo commented on ui/api/endpoint.go
> +				Name:   "sessionDetails",
```suggestion
				Name:   "session_details",
```

2024-02-22 08:32 UTC, rodneyosodo commented on ui/api/endpoint.go
> +				Name:   "sessionDetails",
Also declare it as a variable

2024-02-22 08:32 UTC, rodneyosodo commented on ui/web/templates/navbar.html
> +    console.log(sessionDetails);
Remove debug statements

2024-02-22 08:32 UTC, rodneyosodo commented on ui/api/transport.go
> +	loggedIn, err := readStringQuery(r, loggedInKey, defKey)
maintaining state on query parameters is not ideal

2024-02-22 09:24 UTC, ianmuchyri commented on ui/service.go
> +type SessionDetails struct {
I exported it because it's being used in transport.go
```
		var session ui.SessionDetails
		if err = json.Unmarshal(decodedSession, &session); err != nil {
			return
		}
```

2024-02-22 21:08 UTC, rodneyosodo requested changes

2024-02-22 21:08 UTC, rodneyosodo commented on ui/service.go
> +	ErrSessionType          = errors.New("invalid session type")
We need to handle this on transport too

2024-02-22 21:08 UTC, rodneyosodo commented on ui/api/transport.go
> +	}
```go
req := listDomainsReq{
	Token: sdk.Token{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	},
	status: status,
	page:   page,
	limit:  limit,
}
```

2024-02-22 21:08 UTC, rodneyosodo commented on ui/web/templates/navbar.html
> +    let sessionDetails = JSON.parse(atob(getCookie("session_details")));
wrap this with a try-catch block for error handling

2024-02-26 08:17 UTC, rodneyosodo approved these changes

2024-02-26 09:44 UTC, ianmuchyri commented on ui/web/templates/navbar.html
> +        document.querySelectorAll("#domainName").forEach((element) => {
It's not going to be possible since we need to fetch the data from cookies where we will use javascript and to populate the element with that data we'd have to do that here

2024-02-26 09:57 UTC, merged