MG-182 - Secure token cookies
absmach/magistrala-ui pull request #190
Opened 2024-02-23 14:31 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Add an abstraction API redirect between login and viewing domains that encrypts the tokens that are produced during login and redirects to /domains with the cookies set which are encrypted
![image](https://github.com/absmach/magistrala-ui/assets/100555904/b62161c5-48a2-4aeb-8058-04eb47c7dca5)

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #182 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-02-23 14:31 UTC, ianmuchyri commented
Dependent on this pr: #187

2024-02-26 08:36 UTC, rodneyosodo requested changes

2024-02-26 08:36 UTC, rodneyosodo commented on internal/postgres/postgres.go
> +	Port        string `env:"MG_UI_DB_PORT"           envDefault:"6042"`
Revert. Default Postgres port in `5432`

2024-02-26 08:36 UTC, rodneyosodo commented on ui/api/transport.go
> +	hashkey                 = "5jx4x2Qg9OUmzpP5dbveWQ"
These two should be declared are environment variables https://github.com/absmach/magistrala/blob/d95283d314720fc59035ebd3b254397ce948ab27/cmd/auth/main.go#L58

2024-02-26 08:36 UTC, rodneyosodo commented on go.mod
> +	github.com/gorilla/securecookie v1.1.2 // indirect
Run go mod tidy

2024-02-26 08:36 UTC, rodneyosodo commented on ui/service.go
> +	encodedString := base64.StdEncoding.EncodeToString(data)
Base64 is not a secure way to encode information. Change this too

2024-02-27 13:46 UTC, dborovcanin requested changes

2024-02-27 13:46 UTC, dborovcanin commented on ui/api/transport.go
> +func TokenMiddleware(s *securecookie.SecureCookie) func(http.Handler) http.Handler {
Can we do encryption and decryption of the cookies here or in a separate middleware (and replace request headers with decrypted cookies) so we make this change transparent from the service level?

2024-02-28 12:48 UTC, rodneyosodo requested changes

2024-02-28 12:48 UTC, rodneyosodo commented on cmd/ui/main.go
> +	BlockKey        string          `env:"MG_UI_BLOCK_KEY"        envDefault:"/UtgZjr92jwRY6SPUndHXiyl9QY8qTUy"`
Is this `/` needed?

```suggestion
	BlockKey        string          `env:"MG_UI_BLOCK_KEY"        envDefault:"UtgZjr92jwRY6SPUndHXiyl9QY8qTUy"`
```

2024-02-28 12:48 UTC, rodneyosodo commented on docker/.env
> +MG_HASH_KEY=5jx4x2Qg9OUmzpP5dbveWQ
```suggestion
MG_UI_HASH_KEY=5jx4x2Qg9OUmzpP5dbveWQ
```

2024-03-01 08:42 UTC, rodneyosodo requested changes

2024-03-01 08:42 UTC, rodneyosodo commented on docker/docker-compose.yml
> +      MG_UI_BLOCK_KEY: ${MG_UI_BLOCK_KEY}
Add the two variables to `ui/README.md`

2024-03-01 08:42 UTC, rodneyosodo commented on ui/api/requests.go
> +		fmt.Println("here")
Remove

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +	sessionDetailsKey       = "session_details"
are these used?

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +	Session(s Session, loginStatus string) (Session, error)
This `loginStatus` how is it different from `Session.LoginStatus`

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +	ListUsers(status string, s Session, page, limit uint64) ([]byte, error)
Let's keep `token` / `session` as first argument

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +	token := s.AccessToken
Instead of creating a new variable just use `s.AccessToken`

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +			fmt.Println(err)
remove debug statements

2024-03-01 08:42 UTC, rodneyosodo commented on ui/service.go
> +	token := s.AccessToken
same

2024-03-03 17:39 UTC, rodneyosodo requested changes
Also create a PR on magistrala since it changes https://github.com/absmach/magistrala/blob/0f05c10a3893c903222a65c974d0cd20da861103/docker/.env#L168

2024-03-03 17:39 UTC, rodneyosodo commented on ui/service.go
> +	ViewBootstrap(things Session, idID string) ([]byte, error)
```suggestion
	ViewBootstrap(s Session, id string) ([]byte, error)
```

2024-03-03 17:39 UTC, rodneyosodo commented on ui/service.go
> +		SessionDetails Session
Let's keep this aligned
```suggestion
		Session Session
```

2024-03-04 09:06 UTC, rodneyosodo approved these changes

2024-03-04 12:35 UTC, dborovcanin requested changes

2024-03-04 12:35 UTC, dborovcanin commented on ui/service.go
>  	LoginStatus string `json:"login_status"`
Make an enum.

2024-03-04 13:02 UTC, dborovcanin requested changes

2024-03-04 13:02 UTC, dborovcanin commented on ui/service.go
> +	DomainLoginStatus       LoginStatus = "domain"
Extract to a separate `const` block.

2024-03-04 13:08 UTC, dborovcanin approved these changes

2024-03-04 13:09 UTC, merged