MG-164 - Add input validation to chart modals
absmach/magistrala-ui pull request #193
Opened 2024-02-26 13:57 UTC by 1998-felix

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Adds input validation to the forms present in the create chart modals.

## Which issue(s) does this PR fix/relate to?

- Related Issue #164 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-03-05 13:28 UTC, dborovcanin requested changes
Can we extract the pattern to a shared variable so we can easily change it? We will probably have more of the same check (for not-chart-related) things.

2024-03-06 08:03 UTC, ianmuchyri commented
It shouldn't be showing the green tick if the time is wrong
![image](https://github.com/absmach/magistrala-ui/assets/100555904/c9defa5b-7a09-4215-9090-c6424ea41ca0)

Also, make sure both the start time and end time are not greater than the `now()` time. You can find a way of disabling any time that is greater than `now()` from being selected, or validate it afterward.

2024-03-06 08:11 UTC, ianmuchyri commented on ui/web/templates/charts/linechartmodal.html
>        let form = document.getElementById("create-lineChart-form");
```suggestion
      const form = document.getElementById("create-lineChart-form");
```

2024-03-06 08:20 UTC, ianmuchyri requested changes

2024-03-06 08:20 UTC, ianmuchyri commented on ui/web/templates/charts/linechartmodal.html
> +        invalidTimeFeedback[0].style.color = "red";
```suggestion
        let invalidTimeFeedback = document.querySelector(".invalid-time");
        invalidTimeFeedback.innerHTML = "Stop time should be greater than start time";
        invalidTimeFeedback.style.color = "red";
```

2024-03-06 08:20 UTC, ianmuchyri commented on ui/web/templates/charts/linechartmodal.html
> +        invalidTimeFeedback[0].style.color = "red";
same for the others

2024-03-06 09:20 UTC, rodneyosodo requested changes

2024-03-06 09:20 UTC, rodneyosodo commented on ui/web/templates/charts/alarmcountmodal.html
> +                pattern="{{ .UUIDPattern }}"
Since this value doesn't change why not have it here directly.

2024-03-06 09:20 UTC, rodneyosodo commented on ui/web/templates/charts/alarmstablemodal.html
> +                type="number"
The interval shouldn't be a string something like `1h` or `10s`?

2024-03-06 09:45 UTC, ianmuchyri commented on ui/web/templates/charts/alarmstablemodal.html
> +                type="number"
Currently we are only using intervals in `seconds` for the first iteration. This will be improved in the next iteration to incorporate other intervals, `minutes`, `hours`, `days` etc. This will also have to change based on the `to` and `from`

2024-03-06 10:13 UTC, ianmuchyri commented on ui/web/templates/charts/alarmstablemodal.html
> +                type="number"
But it should still be `string/text` @1998-felix

2024-03-06 13:38 UTC, ianmuchyri commented on ui/web/templates/charts/alarmstablemodal.html
> +                type="number"
@1998-felix  ^

2024-03-08 08:45 UTC, ianmuchyri requested changes

2024-03-08 08:45 UTC, ianmuchyri commented on ui/web/templates/charts/arealinechartmodal.html
> +      invalidTimeInput.classList.remove("is-invalid");
```suggestion
     form.querySelector(".invalid-time").innerHTML="";
    form.querySelector("#stop-time").classList.remove("is-invalid");
```

2024-03-08 08:45 UTC, ianmuchyri commented on ui/web/templates/charts/arealinechartmodal.html
> +      invalidTimeInput.classList.remove("is-invalid");
This simplifies the code. Do this for the other files that do this.

2024-03-08 13:36 UTC, ianmuchyri requested changes

2024-03-08 13:36 UTC, ianmuchyri commented on ui/web/templates/charts/multibarchartmodal.html
> +                    <option value="SUM">Sum</option>
missing `count` aggregation. Check others too if they are missing any.

2024-03-08 13:43 UTC, 1998-felix commented on ui/web/templates/charts/multibarchartmodal.html
> +                    <option value="SUM">Sum</option>
This is done for bar charts and pie charts which I dont think will have the count aggregation as an option

2024-03-08 13:47 UTC, ianmuchyri commented on ui/web/templates/charts/multibarchartmodal.html
> +                    <option value="SUM">Sum</option>
It will. say, I want a pie chart that shows the count of the various messages published by different devices in the same channel.

2024-03-08 14:47 UTC, ianmuchyri requested changes

2024-03-08 14:47 UTC, ianmuchyri commented on ui/web/templates/charts/linechartmodal.html
> +                    class="form-control mb-3 no-validate"
what's with the `no-validate` class and why is it just being used in the line chart and not the other time series charts?

2024-03-08 14:56 UTC, 1998-felix commented on ui/web/templates/charts/linechartmodal.html
> +                    class="form-control mb-3 no-validate"
Should be removed.

2024-03-08 16:03 UTC, ianmuchyri approved these changes

2024-03-08 16:55 UTC, dborovcanin approved these changes

2024-03-08 16:55 UTC, merged