MG-196-Add abstractions for widgets and charts
absmach/magistrala-ui pull request #197
Opened 2024-02-28 07:53 UTC by 1998-felix

# What type of PR is this?

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Add abstractions for widgets and charts

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #196 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-03-04 08:59 UTC, ianmuchyri requested changes

2024-03-04 08:59 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +  }
```suggestion
    this.element = createWidgetElement();
```

2024-03-04 08:59 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +  }
```suggestion
  createWidgetElement() {
    const newItem = document.createElement("div");
    newItem.className = "item item-editable";
    newItem.innerHTML = `
        <div class="item-border">
          <button type="button" class="btn btn-sm" id="removeItem" onclick="removeGridItem(this.parentNode.parentNode);">
            <i class="fas fa-trash-can"></i>
          </button>
          ${this.config.Content}
          </div>
        `;
    if (this.config.Script) {
      let scriptTag = document.createElement("script");
      scriptTag.type = "text/javascript";
      scriptTag.defer = true;
      scriptTag.innerHTML = this.config.Script;
      newItem.appendChild(scriptTag);
    }
     Object.assign(newItem.style, {
      minWidth: this.config.Style.width,
      minHeight: this.config.Style.height
    });
    return newItem;
  }
```

2024-03-04 08:59 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    this.config = new chartTypes[this.chartData.Type](chartData, widgetID);
I don't think there is any need for the chartTypes above. You can pass the actual chart in the chartData.Type and it will be sth like

```suggestion
    this.config = new this.chartData.Type(chartData, widgetID);
```

2024-03-04 09:07 UTC, ianmuchyri requested changes

2024-03-04 09:07 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +class AlarmCount {
```suggestion
class AlarmCount {
  constructor(chartData, widgetID) {
    this.chartData = chartData;
    this.ID = widgetID;
    this.Style = {
      width: "400px",
      height: "175px",
    };
    this.Content = this.#generateContent();
  }

  #generateContent() {
    return `
      <div class="item-content" id="${this.ID}" style="width: ${this.Style.width}; height: ${this.Style.height};">
        <div class="card widgetcard">
          <div class="card-header text-center">
            <h5 class="card-title">Alarm Count</h5>
          </div>
          <div class="card-body text-center">
            <p class="card-text value">35</p>
          </div>
          <div class="card-footer text-center w-100 bg-warning">
            <p class="card-text">Warning Level</p>
          </div>
        </div>
      </div>
    `;
  }
}
```
Do this for the rest of the bootstrap widgets

2024-03-04 09:10 UTC, ianmuchyri requested changes

2024-03-04 09:10 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    <div class="item-content" id="${this.ID}" style="${styleString}">
```suggestion
    <div class="item-content" id="${this.ID}" style="[${styleString}](width: ${this.Style.width}; height: ${this.Style.height};)">
```
No need to declare this as a separate variable

2024-03-04 09:30 UTC, ianmuchyri requested changes

2024-03-04 09:30 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +function editableCanvas() {
```suggestion
function editableCanvas() {
  removeNoWidgetPlaceholder();
  try {
    if (grid) {
      grid.destroy(true);
    }
    grid = new Muuri(gridClass, {
      dragEnabled: true,
      dragHandle: ".item-content",
    });

    if (layout) {
      const gridState = JSON.parse(layout);
      if (gridState) {
        const metadataObj = JSON.parse(metadata);
        gridState.items.forEach(itemData => {
          const chartData = metadataObj[itemData.widgetID];
          const widget = new Widget(chartData, itemData.widgetID);
          const newItem = widget.element;
          const { widgetPosition, widgetSize } = itemData;
          if (widgetPosition) {
            Object.assign(newItem.style, {
              position: "absolute",
              left: widgetPosition.left,
              top: widgetPosition.top,
              minWidth: widgetSize.minWidth,
              minHeight: widgetSize.minHeight,
              transform: widgetPosition.transform || ""
            });
          }
          const contentEl = newItem.querySelector(".item-content");
          Object.assign(contentEl.style, {
            width: widgetSize.width,
            height: widgetSize.height
          });
          grid.add(newItem, { layout: true });
          resizeObserver.observe(newItem);
        });
        grid.layout();
      }
    }
  } catch (error) {
    console.error("Error loading grid state:", error);
  }

  document.getElementById("editableCanvasButton").classList.add("display-none");
  document.getElementById("CanvasButtons").classList.remove("display-none");
  document.querySelectorAll("#removeItem").forEach(item => {
    item.classList.remove("no-opacity");
    item.disabled = false;
  });

  return grid;
}

```

2024-03-04 09:30 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
>        // Add items to the grid
```suggestion
    function loadLayout(savedLayout) {
  try {
    const gridState = JSON.parse(savedLayout);
    if (grid) {
      grid.destroy(true);
    }
    grid = new Muuri(gridClass, {
      dragEnabled: false,
      dragHandle: ".item-content",
    });

    if (gridState.items.length === 0) {
      showNoWidgetPlaceholder();
    } else {
      const metadataObj = JSON.parse(metadata);
      gridState.items.forEach(itemData => {
        const chartData = metadataObj[itemData.widgetID];
        const widget = new Widget(chartData, itemData.widgetID);
        const newItem = widget.element;
        newItem.classList.remove("item-editable");
        const removeButton = newItem.querySelector("#removeItem");
        if (removeButton) {
          removeButton.style.display = "none";
        }
        const { widgetPosition, widgetSize } = itemData;
        if (widgetPosition) {
          Object.assign(newItem.style, {
            position: "absolute",
            left: widgetPosition.left,
            top: widgetPosition.top,
            transform: widgetPosition.transform || ""
          });
        }
        const contentEl = newItem.querySelector(".item-content");
        Object.assign(contentEl.style, {
          width: widgetSize.width,
          height: widgetSize.height
        });

        grid.add(newItem);
      });
    }
    grid.layout();
  } catch (error) {
    console.error("Error loading grid state:", error);
  }
}

```

2024-03-04 09:30 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +
In save layout you can also restructure how you get populate the styles. Something like:
```
const { width, height} = itemContent.style;
const { left, top, transform,minWidth, minHeight } = itemElement.style;
widgetSize: { width, height, minWidth, minHeight },
widgetPosition: { left, top, transform }
```

2024-03-04 11:08 UTC, 1998-felix commented on ui/web/static/js/charts.js
> +    this.config = new chartTypes[this.chartData.Type](chartData, widgetID);
The charttype doesnt match the class name.

2024-03-04 11:57 UTC, ianmuchyri requested changes

2024-03-04 11:57 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    newItem.classList.add("item-editable");
```suggestion
     newItem.className = "item item-editable";
```

2024-03-04 11:57 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
> +          removeButton.style.display = "none";
```suggestion
          removeButton.classList.add("no-opacity");
          removeButton.disabled=true;
```

2024-03-04 12:00 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    this.config = new chartTypes[this.chartData.Type](chartData, widgetID);
You can change in the individual charts so they match e.g instead of `chartData["Type"] = "alarmCount";` you have `chartData["Type"] = "AlarmCount";`

2024-03-04 13:47 UTC, ianmuchyri requested changes

2024-03-04 13:47 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    this.Script = `
This needs a private method too

2024-03-04 13:47 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    this.Content = `
make this a private method:
`#generateContent()` that generates the content

2024-03-04 13:47 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +    this.Content = `
Do this for the other echarts

2024-03-04 14:22 UTC, dborovcanin commented on ui/web/static/js/charts.js
> +          ['Groups', 25.2, 37.1, 41.2, 18, 33.9, 49.1]
Let's keep it as is and move on to per-chart updates for Readers and UI.

2024-03-04 15:30 UTC, ianmuchyri requested changes

2024-03-04 15:30 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +  #generateContent() {
Since there is a lot of repetition in the echarts, we can have a super class called echarts() that the other echarts extend. Then the code would be structured as such

```suggestion
class eChart {
  constructor(widgetID) {
    this.ID = widgetID;
    this.Style = {
      width: "400px",
      height: "400px",
    };
    this.Content = this.#generateContent();
  }
    #generateContent() {
      return `
      <div class="item-content" id="${this.ID}" style="width: ${this.Style.width}; height: ${this.Style.height};">
      </div>
      `;
    }
  
}
class AreaLineChart extends eChart {
  constructor(chartData, widgetID) {
    super(widgetID);
    this.chartData = chartData;
    this.Script = this.#generateScript();
  }

  #generateScript() {
    return `
    var areaLineChart = echarts.init(document.getElementById("${this.ID}"));
    var option = {
        tooltip: {
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            label: {
              backgroundColor: '#6a7985'
            }
          }
        },
        title: {
          text: '${this.chartData.title}',
        },
        legend: {
          data: ['voltage', 'current', 'temperature', 'pressue']
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [
          {
            type: 'category',
            boundaryGap: false,
            data: ['thing1', 'thing2', 'thing3', 'thing4', 'thing5', 'thing6', 'thing7'],
            name: '${this.chartData.xAxisLabel}',
            nameLocation: 'middle',
            nameGap: 25,
          }
        ],
        yAxis: [
          {
            type: 'value',
            name: '${this.chartData.yAxisLabel}',
            nameLocation: 'middle',
            nameGap: 35,
          }
        ],
        series: [
          {
            name: 'voltage',
            type: 'line',
            stack: 'Total',
            areaStyle: {},
            emphasis: {
              focus: 'series'
            },
            data: [120, 132, 101, 134, 90, 230, 210]
          },
          {
            name: 'current',
            type: 'line',
            stack: 'Total',
            areaStyle: {},
            emphasis: {
              focus: 'series'
            },
            data: [220, 182, 191, 234, 290, 330, 310]
          },
          {
            name: 'temperature',
            type: 'line',
            stack: 'Total',
            areaStyle: {},
            emphasis: {
              focus: 'series'
            },
            data: [150, 232, 201, 154, 190, 330, 410]
          },
          {
            name: 'pressure',
            type: 'line',
            stack: 'Total',
            areaStyle: {},
            emphasis: {
              focus: 'series'
            },
            data: [320, 332, 301, 334, 390, 330, 320]
          },
        ]
      };

    areaLineChart.setOption(option);`;
  }
}

class TimeSeriesBarChart extends eChart {
  constructor(chartData, widgetID) {
    super(widgetID);
    this.chartData = chartData;
    this.Script = this.#generateScript();
  }

  #generateScript() {
    return `
    var barChart = echarts.init(document.getElementById("${this.ID}"));
    var option = {
      title: {
        text: '${this.chartData.title}',
        left: 'center',
        show: true
      },
      xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        name: '${this.chartData.xAxisLabel}',
        nameLocation: 'middle',
        nameGap: 35
      },
      yAxis: {
        type: 'value',
        name: '${this.chartData.yAxisLabel}',
        nameLocation: 'middle',
        nameGap: 35
      },
      legend: {
        show: true,
        left: 'right',
      },
        series: [
          {
            data: [120, 200, 150, 80, 70, 110, 130],
            type: 'bar',
            name: '${this.chartData.seriesName}'
          }
        ]
    };

    barChart.setOption(option);`;
  }
}
```

2024-03-05 09:11 UTC, ianmuchyri requested changes

2024-03-05 09:11 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
>          }
```suggestion
      
```

2024-03-05 09:11 UTC, ianmuchyri commented on ui/web/static/js/singleDashboard.js
>          }
No need for this since this is done during saving of the layout

2024-03-05 11:16 UTC, ianmuchyri approved these changes

2024-03-05 12:47 UTC, dborovcanin requested changes
Rename `singleDashboard.js` to `dashboard.js`.

2024-03-05 13:13 UTC, dborovcanin approved these changes

2024-03-05 13:22 UTC, merged