NOISSUE - Add Google as an OAuth2.0 Provider
absmach/magistrala-ui pull request #198
Opened 2024-02-28 07:59 UTC by rodneyosodo

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

- **New Features**
	- Integrated Google OAuth2 for user authentication, enhancing security and user experience.
	- Provided Google sign-in/sign-up options on login and registration pages.

- **Documentation**
	- Updated README and documentation to include Google OAuth-related environment variables and OAuth2 functionality details.

## Which issue(s) does this PR fix/relate to?

No issue

## Have you included tests for your changes?

- [x] Yes. Tested manually
- [ ] No, and this is why: 

## Did you document any new/modified functionality?

- [x] Yes
- [ ] No, and this is why: 

### Notes

Linked to https://github.com/absmach/magistrala/pull/2103

2024-02-28 10:24 UTC, dborovcanin requested changes

2024-02-28 10:24 UTC, dborovcanin commented on ui/service.go
> +}
There is no need for this; you can use the Oauth2 provider directly in the API layer, and remove it from the service.

2024-02-28 10:24 UTC, dborovcanin commented on ui/oauth2/oauth2.go
> +type Handler interface {
Rename to `Provider` and remove the provider enum - it isn't needed if we don't use the service layer.

2024-02-28 12:45 UTC, ianmuchyri approved these changes

2024-02-29 11:42 UTC, dborovcanin approved these changes

2024-02-29 11:42 UTC, merged