NOISSUE - Update Chart Data
absmach/magistrala-ui pull request #199
Opened 2024-03-01 15:03 UTC by Musilah

# What type of PR is this?
This is a Feature that updates the dashboards charts to be able to get data from the backend. 

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
It allows for the time series line chart to fetch data from back end and populates it. 

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

- [ ] Yes
- [X] No 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No 

### Notes

2024-03-05 15:08 UTC, 1998-felix commented on ui/service.go
> +		return []byte{}, errors.Wrap(err, ErrExecTemplate)
Could you wrap with a more suitable err?

2024-03-06 06:39 UTC, 1998-felix approved these changes

2024-03-06 09:01 UTC, rodneyosodo requested changes

2024-03-06 09:01 UTC, rodneyosodo commented on ui/api/logging.go
> +			slog.Any("page metadata", mpgm),
```suggestion
			slog.Any("page_metadata", mpgm),
```

2024-03-06 09:01 UTC, rodneyosodo commented on ui/api/errors.go
> +	errCredentials            = errors.New("missing or invalid credentials provided")
```suggestion
	errInvalidCredentials            = errors.New("missing or invalid credentials provided")
```

2024-03-06 09:08 UTC, ianmuchyri commented on ui/service.go
> +	FetchChartData(token string, channelID string, mpgm sdk.MessagePageMetadata) ([]byte, error)
yes, they call the same SDK function but don't return the same response. `ReadMessages` renders an `HTML` template, while `FetchChartData` renders a `JSON` object that will be used in populating the chart. No HTML is being rendered in the latter.

2024-03-06 09:21 UTC, dborovcanin approved these changes

2024-03-06 09:21 UTC, dborovcanin commented on ui/service.go
> +	FetchChartData(token string, channelID string, mpgm sdk.MessagePageMetadata) ([]byte, error)
This is OK at the moment, but in the future, we should consider using JS SDK to access MG directly from our browser. That will require changes in session handling due to encrypted cookies.

2024-03-06 09:44 UTC, rodneyosodo requested changes

2024-03-06 09:44 UTC, rodneyosodo commented on ui/service.go
> +	ReadMessages(s Session, channelID, thingKey string, page uint64, mpgm sdk.MessagePageMetadata) ([]byte, error)
Isn't the page contained in `MessagePageMetadata` as offset?

2024-03-06 10:19 UTC, rodneyosodo requested changes

2024-03-06 10:19 UTC, rodneyosodo commented on ui/service.go
> +	msg, err := us.sdk.ReadMessages(mpgm, channelID, token)
```suggestion
	msg, sdkErr := us.sdk.ReadMessages(mpgm, channelID, token)
```

The for json leave it as `err`

2024-03-06 10:19 UTC, rodneyosodo commented on ui/api/requests.go
> -	if req.page == 0 {
No need to remove this check just use a different variable

2024-03-06 10:31 UTC, rodneyosodo requested changes

2024-03-06 10:31 UTC, rodneyosodo commented on ui/api/metrics.go
> +		mm.counter.With("method", "fetch_reader_data").Add(1)
```suggestion
		mm.counter.With("method", "fetch_chart_data").Add(1)
```

2024-03-06 10:33 UTC, rodneyosodo approved these changes

2024-03-06 15:24 UTC, dborovcanin approved these changes

2024-03-06 15:24 UTC, merged