MG-212 - Update Cards to fetch data from the back-end
absmach/magistrala-ui pull request #220
Opened 2024-03-08 16:55 UTC by Musilah

# What type of PR is this?

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
This PR updates the cards to be able to fetch data from the back-end. 

## Which issue(s) does this PR fix/relate to?

- Resolves #212

## Have you included tests for your changes?

- [ ] Yes
- [X] No 

## Did you document any new/modified functionality?

- [ ] Yes
- [X] No

### Notes

2024-03-14 09:50 UTC, ianmuchyri requested changes

2024-03-14 09:50 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +            "/data?channel=${this.chartData.channel}"+
add `prefix` support

2024-03-14 09:58 UTC, ianmuchyri requested changes

2024-03-14 09:58 UTC, ianmuchyri commented on ui/web/templates/charts/entitycountmodal.html
> +                <div class="mb-3">
The domain is implied

2024-03-14 09:58 UTC, ianmuchyri commented on ui/web/templates/charts/entitycountmodal.html
> +                  <label for="channel-id" class="form-label">Channel ID</label>
This is not the right format. You are being too specific. Entity count can be `things`, `channels`, `groups`, `channel-things`,  etc. You should allow the user to select the entity they want to count for. If they want the channels a thing is connected to e.g. if they select thing-channels, they will be given an input for the entity id, if it is entity-specific.

2024-03-19 08:48 UTC, ianmuchyri approved these changes

2024-03-20 08:46 UTC, dborovcanin approved these changes

2024-03-20 08:46 UTC, merged