MG-211 - Update time series bar chart fo fetch data from back-end
absmach/magistrala-ui pull request #224
Opened 2024-03-11 13:20 UTC by 1998-felix

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Populate the time series bar chart with data from the back-end

## Which issue(s) does this PR fix/relate to?

- Related Issue #211 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-03-13 11:05 UTC, ianmuchyri requested changes

2024-03-13 11:05 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +      to: ${this.chartData.stopTime / 1000},
```suggestion
      from: ${this.chartData.startTime},
      to: ${this.chartData.stopTime},
```

2024-03-14 07:51 UTC, ianmuchyri requested changes

2024-03-14 07:51 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +          console.log(data);
remove logs

2024-03-14 07:52 UTC, ianmuchyri commented
Also make it such that aggregation is not compulsory. Check how it was changed in the line chart. Aggregation is not compulsory, but if a user selects aggregation, then they have to select interval

2024-03-14 08:16 UTC, ianmuchyri requested changes

2024-03-14 08:16 UTC, ianmuchyri commented on ui/web/static/js/charts.js
> +          const apiEndpoint = "/data?channel=" + chartData.channel +
add `prefix`

2024-03-14 10:00 UTC, ianmuchyri requested changes

2024-03-14 10:00 UTC, ianmuchyri commented on ui/web/templates/charts/barchartmodal.html
> +        aggregationTypeInput.addEventListener("change", toggleUpdateInterval);
```
 toggleUpdateInterval();
 aggregationTypeInput.addEventListener("change", toggleUpdateInterval);
```
what is the difference here. Since the function has been called by default in the first instance

2024-03-15 11:29 UTC, ianmuchyri requested changes

2024-03-15 11:29 UTC, ianmuchyri commented on ui/web/templates/charts/barchartmodal.html
> +          chartData[pair[0]] = inputDate.getTime() * 1e6;
r
```suggestion
          chartData[pair[0]] = inputDate.getTime() ;
```

2024-03-18 09:30 UTC, ianmuchyri requested changes

2024-03-18 09:30 UTC, ianmuchyri commented on ui/web/templates/charts/barchartmodal.html
>        for (var pair of formData.entries()) {
```suggestion
     for (let [name, value] of formData) {
```

2024-03-18 15:20 UTC, dborovcanin approved these changes

2024-03-19 08:46 UTC, ianmuchyri requested changes

2024-03-19 08:46 UTC, ianmuchyri commented on ui/web/static/js/charts.js
>        xAxis: {
```suggestion
      tooltip: {
        trigger: 'axis'
      },
      xAxis: {
```

2024-03-19 08:46 UTC, ianmuchyri commented on ui/web/static/js/charts.js
>        xAxis: {
for sth like this 
![image](https://github.com/absmach/magistrala-ui/assets/100555904/b0a3c9f4-4a29-4efb-bd60-c48975728351)

2024-03-21 15:42 UTC, dborovcanin approved these changes

2024-03-21 15:42 UTC, merged