NOISSUE - Add Dashboard Respository Tests
absmach/magistrala-ui pull request #234
Opened 2024-03-12 11:59 UTC by rodneyosodo

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

Add test for dashboards

## Which issue(s) does this PR fix/relate to?

- Related Issue #15 

## Have you included tests for your changes?

- [x] Yes
- [ ] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: No documentation needed 

### Notes

2024-03-12 15:15 UTC, ianmuchyri requested changes

2024-03-12 15:15 UTC, ianmuchyri commented on cmd/ui/main.go
> +	if err := env.Parse(&cfg); err != nil {
```suggestion
	if err := env.Parse(&dbConfig); err != nil {
```

2024-03-14 10:37 UTC, dborovcanin requested changes

2024-03-14 10:37 UTC, dborovcanin commented on postgres/dashboards.go
> +	Name        *string   `db:"name"`
Why did you change to pointer?

2024-03-14 11:13 UTC, rodneyosodo commented on postgres/dashboards.go
> +	Name        *string   `db:"name"`
Because the database schema checks if the value is null, an empty string is valid but undesirable.

2024-03-14 14:52 UTC, dborovcanin commented on postgres/init.go
> +						id VARCHAR(36) NOT NULL CHECK (id <> ''),
Make ID unique and primary key.

2024-03-14 15:16 UTC, dborovcanin approved these changes

2024-03-14 15:16 UTC, merged