NOISSUE - Fix send messages page time format
absmach/magistrala-ui pull request #238
Opened 2024-03-13 16:31 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
fix read messages page time format to be precision independent.

## Which issue(s) does this PR fix/relate to?

NOISSUE

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-03-14 14:35 UTC, rodneyosodo requested changes

2024-03-14 14:49 UTC, rodneyosodo approved these changes

2024-03-14 22:08 UTC, dborovcanin commented on ui/service.go
> +	MilliToNanoConverter = math.Pow10(6)
Use to `MilliToNanoRatio = 1e6`.

2024-03-15 09:29 UTC, dborovcanin approved these changes

2024-03-15 09:29 UTC, merged