MG-42 - Remove creation of a channel with a parent channel
absmach/magistrala-ui pull request #250
Opened 2024-03-19 09:25 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Removes the ability for a user to create a channel with another channel as the parent. This is because this is not supported on the magistrala core.

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #42 
- Resolves #44 

## Have you included tests for your changes?

- [ ] Yes
- [ ] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [ ] No, and this is why: 

### Notes

2024-03-19 14:06 UTC, 1998-felix requested changes
![image](https://github.com/absmach/magistrala-ui/assets/57312311/fc94301e-fe19-4c10-a6f5-7885d028293e)
Is this still required?

2024-03-19 16:00 UTC, 1998-felix approved these changes

2024-03-19 18:55 UTC, Musilah approved these changes

2024-03-21 14:35 UTC, dborovcanin approved these changes

2024-03-21 14:35 UTC, merged