MG-24 - Switch from Organization to Domain
absmach/magistrala-ui pull request #27
Opened 2023-12-04 12:51 UTC by ianmuchyri

# What type of PR is this?

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Switch from using organization to domain in Magistrala

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #24 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2023-12-07 15:14 UTC, rodneyosodo requested changes

2023-12-07 15:14 UTC, rodneyosodo commented on ui/api/endpoint.go
> +			sdk.Domain{
Extract domain to a variable

2023-12-07 15:28 UTC, rodneyosodo requested changes

2023-12-07 15:28 UTC, rodneyosodo commented on ui/api/endpoint.go
> +		err := svc.CreateDomain(req.token, domain)
Inline error check

2023-12-07 15:32 UTC, rodneyosodo approved these changes
LGTM

2023-12-13 16:28 UTC, dborovcanin approved these changes

2023-12-13 16:28 UTC, merged