NOISSUE - Abstract list data-structure on input form
absmach/magistrala-ui pull request #32
Opened 2023-12-13 07:54 UTC by SammyOina

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

Allows input of list items in a user-friendly way without revealing the underlying datastructure

## Which issue(s) does this PR fix/relate to?

None

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: Changes are on user experience

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: only minor changes to ui

### Notes

This could also be used for metadata input

2023-12-18 08:30 UTC, ianmuchyri requested changes

2023-12-18 08:30 UTC, ianmuchyri commented on ui/web/template/navbar.html
> +                <div id="tagsList" onclick="deleteItem(event)"></div>
It doesn't seem to be displaying the tags properly
![Uploading image.png…]()

2023-12-18 08:30 UTC, ianmuchyri commented on ui/web/template/things.html
> +                              <div id="tagsList" onclick="deleteItem(event)"></div>
this is not shown on the modal completely 
![image](https://github.com/absmach/magistrala-ui/assets/100555904/f6dcef78-4bcc-42d9-8ee5-1ba838442e4b)

2023-12-18 13:51 UTC, SammyOina commented on ui/web/template/navbar.html
> +                <div id="tagsList" onclick="deleteItem(event)"></div>
I don't have the same problem, might be a browser issue on your end

2023-12-18 13:52 UTC, SammyOina commented on ui/web/template/things.html
> +                              <div id="tagsList" onclick="deleteItem(event)"></div>
what is not shown, list items are only visible after being added

2023-12-18 13:54 UTC, ianmuchyri commented on ui/web/template/things.html
> +                              <div id="tagsList" onclick="deleteItem(event)"></div>
I had already added them, and they were not being displayed

2023-12-18 13:55 UTC, SammyOina commented on ui/web/template/things.html
> +                              <div id="tagsList" onclick="deleteItem(event)"></div>
not sure what issue you are having but I have added a preview of the change on the PR description

2023-12-19 08:26 UTC, rodneyosodo requested changes

2023-12-19 08:26 UTC, rodneyosodo commented on ui/web/static/js/listUtils.js
> +  alert("JSON data ready to submit:\n" + jsonData);
I don't think we need this alert

2023-12-19 08:26 UTC, rodneyosodo commented on ui/web/static/js/listUtils.js
> +function generateColor() {
We can generate truly random colours rather than repeating after 4 items 
![image](https://github.com/absmach/magistrala-ui/assets/28790446/eacd00fa-4ce7-4626-9deb-a42f0aa45a78)

2023-12-19 08:33 UTC, ianmuchyri requested changes

2023-12-19 08:33 UTC, ianmuchyri commented on ui/web/template/bootstraps.html
> +      <script src="/js/listUtils.js"></script>
since you import this script in `navbar.html` which is called in all the other pages, there is no need to import this again. Remove the import in all other files apart from `navbar.html`.
It results in this error on the browser: 
```
Uncaught SyntaxError: Identifier 'colorIndex' has already been declared (at listUtils.js:1:1)
```

2023-12-19 09:13 UTC, SammyOina commented on ui/web/static/js/listUtils.js
> +function generateColor() {
truly random colors would be a bad idea as it would risk visibility of the text and accounting for both is simply over-engineered

2023-12-19 09:29 UTC, ianmuchyri commented
It shouldn't reflect if a user presses the enter button without having any data as shown below
![image](https://github.com/absmach/magistrala-ui/assets/100555904/758f8905-27e1-4a56-9c13-8bcd736d1636)

Those dots are if I press the enter button without having any tags

2023-12-19 09:30 UTC, rodneyosodo commented on ui/web/static/js/listUtils.js
> +function generateColor() {
Not really this is an example https://css-tricks.com/snippets/javascript/random-hex-color/

2023-12-19 14:17 UTC, ianmuchyri requested changes

2023-12-19 14:17 UTC, ianmuchyri commented on ui/web/template/users.html
>                                <label for="tags" class="form-label">Tags</label>
```suggestion
                              <label for="userTags" class="form-label">Tags</label>
```

2023-12-19 14:17 UTC, ianmuchyri commented on ui/web/template/things.html
>                                <label for="tags" class="form-label">Tags</label>
```suggestion
                              <label for="thingsTags" class="form-label">Tags</label>
```

2023-12-19 19:10 UTC, rodneyosodo requested changes

2023-12-19 19:10 UTC, rodneyosodo commented on ui/web/static/js/listUtils.js
> +function generateColor() {
Single colour like Kubernetes tags as discussed

2023-12-20 11:06 UTC, ianmuchyri commented
There is no more color 
![image](https://github.com/absmach/magistrala-ui/assets/100555904/3237963d-19fc-4922-9fba-68adbfe1ce96)

2023-12-20 11:07 UTC, ianmuchyri commented
also check why in this modal, it does not work as intended. I cannot see the tags at the top
![image](https://github.com/absmach/magistrala-ui/assets/100555904/7799c832-a788-45ed-bfdd-14f418c728da)

2023-12-21 08:13 UTC, ianmuchyri commented on ui/web/static/js/listUtils.js
> +      newItem.className = "mb-2 btn btn-primary highlight-list-item";
Is there a reason why you removed the previous colors? They looked much better than the plain blue color that's being introduced by `btn-primary`

2023-12-21 14:09 UTC, ianmuchyri requested changes

2023-12-21 14:09 UTC, ianmuchyri commented on ui/web/template/things.html
> +                                id="thingTags"
changing the tag id here results in an error in the validation scripts 
![image](https://github.com/absmach/magistrala-ui/assets/100555904/a1efdca0-381a-459b-9d93-869f62687c60)

same case for users. Since you already changed the id for the common form in navbar, you could leave these as they were or change the validation section too

2023-12-28 10:34 UTC, ianmuchyri approved these changes
LGTM

2024-01-10 10:03 UTC, dborovcanin commented
Please rebase.

2024-01-10 10:28 UTC, SammyOina commented
> Please rebase.

@dborovcanin I have rebased

2024-01-10 10:29 UTC, SammyOina commented
> Please rebase.

@dborovcanin I have rebased

2024-01-11 08:24 UTC, rodneyosodo requested changes
Let's do it also when updating tags

![image](https://github.com/absmach/magistrala-ui/assets/28790446/0b4571cb-4f60-4fee-866c-f5b93db6abc7)

2024-01-11 08:26 UTC, SammyOina commented
> Let's do it also when updating tags
> 
> ![image](https://github.com/absmach/magistrala-ui/assets/28790446/0b4571cb-4f60-4fee-866c-f5b93db6abc7)
> 

Updates use tables it's a bit different and would require a separate PR

2024-01-11 08:30 UTC, rodneyosodo commented
> > Let's do it also when updating tags
> 
> Updates use tables it's a bit different and would require a separate PR

Can you create an issue for that

2024-01-11 11:26 UTC, dborovcanin approved these changes

2024-01-11 11:27 UTC, merged