MG-28 - Invitations
absmach/magistrala-ui pull request #33
Opened 2023-12-13 08:24 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?

Implements invitations to the UI to enable a domain admin to be able to invite a user to a domain.
## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #28 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2023-12-18 09:02 UTC, rodneyosodo requested changes
![image](https://github.com/absmach/magistrala-ui/assets/28790446/ee082f0d-9816-480e-8829-6be62f6615ac)

2023-12-18 12:03 UTC, rodneyosodo requested changes

2023-12-18 12:03 UTC, rodneyosodo commented on ui/web/static/css/styles.css
> +}
Add empty line

2023-12-18 12:21 UTC, rodneyosodo requested changes

2023-12-18 12:21 UTC, rodneyosodo commented on ui/service.go
> +	DomainInvitations(token, domainID string, page, limit uint64) ([]byte, error)
Since `DomainInvitations` and `Invitations` are almost the same why not use one function signature where `domainID` can be empty? Something like

```go
Invitations(token, domainID string, page, limit uint64) ([]byte, error)
```

2023-12-18 13:30 UTC, rodneyosodo requested changes

2023-12-18 13:30 UTC, rodneyosodo commented on ui/service.go
> +	if domainID == "" {
Use switch

2023-12-18 13:42 UTC, rodneyosodo approved these changes
LGTM

2023-12-19 08:56 UTC, dborovcanin approved these changes

2023-12-19 08:56 UTC, merged