MG-11 - Implementation of messaging feature on the UI
absmach/magistrala-ui pull request #73
Opened 2024-01-09 13:16 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Proper implementation of the messaging feature (both send and read messages from db) in the UI. 
Previously, we did not have the send message feature, and for the read message a user had to manually enter the channel ID and thing Key to be able to read messages stored in the database.
In this implementation, the messaging features are combined into one page, which is accessed via the thingsChannel page. In this page, the user clicks on the messaging icon and they are moved to the messages page. Here they can be able to view all the messages stored in the database that have been sent to that channel.They can also be able to send a test message to the channel using the device they had accessed the channel with.

## Which issue(s) does this PR fix/relate to?

- Resolves #11 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes
![image](https://github.com/absmach/magistrala-ui/assets/100555904/3a2ec773-8e86-4ade-8542-6b8bd0d8e7b0)
![image](https://github.com/absmach/magistrala-ui/assets/100555904/3d49bb08-1e89-4920-a327-178276db2699)
![image](https://github.com/absmach/magistrala-ui/assets/100555904/ff0a24d0-dbf9-428b-826e-1da2338c3d84)
![image](https://github.com/absmach/magistrala-ui/assets/100555904/98c784bd-d10f-4446-a9c2-70bbb9a9f69c)
![image](https://github.com/absmach/magistrala-ui/assets/100555904/0030a372-e117-4738-b351-582f55dcf9a5)

2024-01-10 09:11 UTC, rodneyosodo requested changes
Pagination doesn't work. Publish 100 messages and try and go to the second page

2024-01-10 09:18 UTC, rodneyosodo requested changes

2024-01-10 09:18 UTC, rodneyosodo commented on ui/service.go
> +	var thingKey string
No need to read messages using thing. You can use the user token to read messages from a channel https://github.com/absmach/magistrala-old/pull/199

2024-01-10 09:18 UTC, rodneyosodo commented on ui/api/requests.go
> +type messagesReq struct {
revert its name to `readMessageReq`

2024-01-10 09:18 UTC, rodneyosodo commented on ui/service.go
> +	Messages(token, chID, thKey string, page, limit uint64) ([]byte, error)
Revert its name to `ReadMessages` same as other occurrences

2024-01-10 11:03 UTC, ianmuchyri commented
> Pagination doesn't work. Publish 100 messages and try and go to the second page

will be fixed in this pr: https://github.com/absmach/magistrala-ui/pull/77

2024-01-10 12:46 UTC, ianmuchyri commented
> Pagination doesn't work. Publish 100 messages and try and go to the second page

we don't have pagination in Magistrala `readMessage`

2024-01-10 13:30 UTC, ianmuchyri commented
> > Pagination doesn't work. Publish 100 messages and try and go to the second page
> 
> we don't have pagination in Magistrala `readMessage`

It will be resolved by this pr: https://github.com/absmach/magistrala/pull/2055

2024-01-11 08:37 UTC, rodneyosodo requested changes

2024-01-11 08:37 UTC, rodneyosodo commented on ui/service.go
> +	ReadMessages(token, chID, thKey string, page, limit uint64) ([]byte, error)
```suggestion
	ReadMessages(token, chID string, page, limit uint64) ([]byte, error)
```
No need for thingKey

2024-01-11 08:41 UTC, ianmuchyri commented on ui/service.go
> +	ReadMessages(token, chID, thKey string, page, limit uint64) ([]byte, error)
the thing key is passed back to the HTML template to be used by the t`est channel modal` for publishing to the channel

2024-01-11 09:04 UTC, ianmuchyri commented
the CI failure will be resolved by this https://github.com/absmach/agent/pull/4

2024-01-12 10:52 UTC, rodneyosodo requested changes

2024-01-12 10:52 UTC, rodneyosodo commented on ui/api/transport.go
> +	baseName                = "test-"
No need for this as it prefix messages from UI

2024-01-12 10:52 UTC, rodneyosodo commented on ui/api/transport.go
> +	message := struct {
Add this on `publishReq` struct

2024-01-12 15:30 UTC, rodneyosodo approved these changes

2024-01-21 16:18 UTC, dborovcanin requested changes
Please resolve conflicts so we can test and review.

2024-01-23 12:43 UTC, merged