MG-74 - Update metadata styling for the inner tables
absmach/magistrala-ui pull request #76
Opened 2024-01-09 15:05 UTC by ianmuchyri

# What type of PR is this?

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Update the styling of the inner tables that had not been updated to the latest changes

## Which issue(s) does this PR fix/relate to?

- Resolves #74 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-01-10 09:04 UTC, rodneyosodo requested changes
Have a look at this edge case 

![image](https://github.com/absmach/magistrala-ui/assets/28790446/4c8f1114-7c50-483b-a410-329c9b9c3195)


You can test using this json structure

```json
 {
    "_id": "659e5cb57a0419df0286e45e",
    "index": 0,
    "guid": "d5eca234-7f62-4f99-8d45-7718c818d1ba",
    "isActive": true,
    "balance": "$3,406.01",
    "picture": "http://placehold.it/32x32",
    "age": 40,
    "eyeColor": "brown",
    "name": "Augusta Morales",
    "gender": "female",
    "company": "FROSNEX",
    "email": "augustamorales@frosnex.com",
    "phone": "+1 (932) 525-3174",
    "address": "779 Ocean Court, Fedora, Maryland, 2180",
    "about": "Ut do officia ipsum tempor deserunt laborum dolor irure in. Eiusmod reprehenderit duis sint incididunt dolore dolor irure exercitation nostrud. Enim aliqua nulla ut adipisicing qui. Exercitation culpa sit amet veniam mollit velit cillum amet anim veniam eu deserunt. Consequat anim nostrud duis sunt est sit velit pariatur eu nostrud enim aliqua.\r\n",
    "registered": "2019-11-07T07:28:58 -03:00",
    "latitude": 76.180218,
    "longitude": 138.835929,
    "tags": [
      "dolore",
      "adipisicing",
      "minim",
      "do",
      "ad",
      "fugiat",
      "excepteur"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Mercado Ramirez"
      },
      {
        "id": 1,
        "name": "Kayla Green"
      },
      {
        "id": 2,
        "name": "Gamble Lowe"
      }
    ],
    "greeting": "Hello, Augusta Morales! You have 10 unread messages.",
    "favoriteFruit": "strawberry"
  }
```

The text is overflowing can we have max-width set to truncate long key-value pairs

2024-01-11 08:29 UTC, rodneyosodo requested changes
What about domain metadata? It fails to update it

2024-01-11 08:29 UTC, rodneyosodo commented on ui/web/static/css/styles.css
> +}
new line

2024-01-11 08:43 UTC, ianmuchyri commented
> What about domain metadata? It fails to update it

Also a problem with Magistrala endpoint, One cannot update anything for a domain

2024-01-11 12:06 UTC, rodneyosodo approved these changes

2024-01-18 10:34 UTC, dborovcanin approved these changes

2024-01-18 10:34 UTC, merged