MG-18 - Add cookie expiration time
absmach/magistrala-ui pull request #83
Opened 2024-01-15 10:14 UTC by ianmuchyri

# What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Add the ability to set token expiration time from the `.env` file. These values are then added to the cookie `max-age` variable

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #18 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-01-16 11:01 UTC, fbugarski commented
LGTM

2024-01-17 08:49 UTC, rodneyosodo commented on docker/.env
> +MG_REFRESH_TOKEN_TTL=24h
Why do we need this and UI is not generating any token? Shouldn't this information be decoded from the token itself?

2024-01-18 09:43 UTC, rodneyosodo requested changes

2024-01-18 09:43 UTC, rodneyosodo commented on ui/api/endpoint.go
> +					MaxAge:   exp,
Why not use the `Expires` field since we have the time when the token expires rather than subtracting `time.Now` ?

2024-01-18 13:44 UTC, rodneyosodo requested changes

2024-01-18 13:44 UTC, rodneyosodo commented on ui/api/endpoint.go
> +					Expires:  exp,
This expiry time for refresh token but not access token

2024-01-18 14:37 UTC, ianmuchyri commented on ui/api/endpoint.go
> +					Expires:  exp,
yes, I explained the reason behind my doing this on the UI channel. Check the conversation we had with Dusan

2024-01-23 12:53 UTC, ianmuchyri commented on ui/api/endpoint.go
> +					Expires:  exp,
This was resolved based on this explanation:

```
For access_token with 15min

- if token is non-existent and refresh_token is there use refresh_token to fetch new token i.e will not send you to login page
- if token is non-existent and refresh_token is non-existent send user to login page
```

2024-01-23 13:02 UTC, dborovcanin commented on ui/api/endpoint.go
> +					Expires:  exp,
https://github.com/absmach/magistrala-ui/issues/18#issuecomment-1906001123

2024-01-23 13:02 UTC, dborovcanin approved these changes

2024-01-23 13:45 UTC, merged