MG-84 - Update logger to use slog package
absmach/magistrala-ui pull request #86
Opened 2024-01-16 07:48 UTC by ianmuchyri

# What type of PR is this?

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## What does this do?
Update our logger from using Magistrala logger to using the go slog package

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #84 

## Have you included tests for your changes?

- [ ] Yes
- [x] No, and this is why: 

## Did you document any new/modified functionality?

- [ ] Yes
- [x] No, and this is why: 

### Notes

2024-01-17 08:47 UTC, rodneyosodo requested changes

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		email := slog.String("email", email)
Email and tokens are private information. I don't think they should be exposed for observability

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		user := slog.String("user", id)
```suggestion
		user := slog.String("user_id", id)
```

Same to other cases

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> -		message := fmt.Sprintf("Method create_things took %s to complete", time.Since(begin))
Add number of things

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		thing := slog.String("thing", id)
Do something like, same as other cases

```go
thing := slog.Group("thing", slog.String("id", id), slog.Any("tags", thing.Tags))
```

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		users := slog.String("users", fmt.Sprintf("%v", req.UserIDs))
Logs should be json compatible, try and check `slog.Any` if it produces better logs than this formating

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		duration := slog.String("duration", time.Since(begin).String())
same

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		channel := slog.String("channel", connIDs.ChannelID)
```suggestion
		channel := slog.String("channel_id", connIDs.ChannelID)
```

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		thing := slog.String("thing", connIDs.ThingID)
```suggestion
		thing := slog.String("thing_id", connIDs.ThingID)
```

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		duration := slog.String("duration", time.Since(begin).String())
Have a look at something like for many attributes
```go
func (lm *loggingMiddleware) ListChannelUsers(token, channelID, relation string, page, limit uint64) (b []byte, err error) {
	defer func(begin time.Time) {
		args := []interface{}{
			slog.String("duration", time.Since(begin).String()),
			slog.String("channel_id", channelID),
			slog.String("relation", relation),
			slog.Uint64("page", page),
			slog.Uint64("limit", limit),
		}
		if err != nil {
			args = append(args, slog.String("err", err.Error()))
			lm.logger.Error("List channel users failed to complete successfully", args...)
			return
		}
		lm.logger.Info("List channel users completed successfully", args...)
	}(time.Now())

	return lm.svc.ListChannelUsers(token, channelID, relation, page, limit)
}
```

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		channel := slog.String("group", chID)
```suggestion
		channel := slog.String("channel_id", chID)
```

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		thing := slog.String("thing", config[0].ThingID)
This is not safe

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		thing := slog.String("thing", config.ThingID)
Add connection details

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		thing := slog.String("thing", id)
Add command

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		entity := slog.String("entity", entityType)
Group

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		duration := slog.String("duration", time.Since(begin).String())
Does `errMsg` contain `err` ?

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		page := slog.Uint64("page", page)
Add status

2024-01-17 08:47 UTC, rodneyosodo commented on ui/api/logging.go
> +		duration := slog.String("duration", time.Since(begin).String())
Add more information

2024-01-18 09:18 UTC, rodneyosodo requested changes

2024-01-18 09:18 UTC, rodneyosodo commented on ui/api/logging.go
> +			lm.logger.Error("View index page failed to complete successfully", slog.String("err", err.Error()), duration)
Use something like
```go
args = append(args, slog.Any("error", err))
```

It produces this output which might be useful for wrapped error messages

```json
{"time":"2024-01-18T09:01:13.948139963Z","level":"ERROR","msg":"Token request failed to complete successfully","error":{"error":"failed to create token","message":"invalid user id or secret"},"duration":"50.585457ms"}
```

2024-01-18 09:18 UTC, rodneyosodo commented on ui/api/logging.go
> +		duration := slog.Any("duration", time.Since(begin))
```go
slog.String("duration", time.Since(begin).String()),
```

2024-01-18 09:18 UTC, rodneyosodo commented on ui/api/logging.go
> +			slog.Group("config", slog.String("thing_id", config.ThingID), slog.String("client_cert", config.ClientCert), slog.String("client_key", config.ClientKey), slog.String("ca_cert", config.CACert)),
Remove `client_cert`, `client_key` and `ca_cert` they are usually too big and also are sensitive information

2024-01-18 09:18 UTC, rodneyosodo commented on ui/api/logging.go
> +			slog.String("entity", entityType),
Group entity then have type and name

```go
slog.Group("entity", slog.String("type", entityType), slog.String("name", entityName)),
```

2024-01-18 09:18 UTC, rodneyosodo commented on ui/api/logging.go
> +			slog.String("error_message", errMsg),
```suggestion
			slog.String("error", errMsg),
```

I think `error` is just fine

2024-01-18 13:22 UTC, rodneyosodo approved these changes

2024-01-22 10:30 UTC, Musilah commented on ui/api/logging.go
>  	return lm.svc.DeleteBootstrap(token, id)
Do the same for `UpdateBootstrapState``

2024-01-22 22:38 UTC, Musilah approved these changes

2024-01-23 12:27 UTC, dborovcanin approved these changes

2024-01-23 12:27 UTC, merged